### ISSUE TITLE
OpenVAS result import issue

### ISSUE THREAD

**Issue by lospoelos** [infobyte/faraday_agent_dispatcher#12]
Hi team,
I get the following error in the faraday_agent_dispatcher when running an OpenVAS scan:

```
2022-11-03 10:23:37,707 - faraday_agent_dispatcher - INFO {MainThread} [dispatcher.py:416 - run_once()]  Running openvas executor
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/faraday_agent_dispatcher/static/executors/official/gvm_openvas.py", line 168, in <module>
    main()
  File "/usr/local/lib/python3.10/dist-packages/faraday_agent_dispatcher/static/executors/official/gvm_openvas.py", line 145, in main
    report = gmp.get_report(
TypeError: ReportsMixin.get_report() got an unexpected keyword argument 'filter'
stderr sent empty data,
2022-11-03 10:55:20,521 - faraday_agent_dispatcher - INFO {MainThread} [executor_helper.py:157 - end_f()]  Data sent to bulk create
stdout sent empty data,
2022-11-03 10:55:20,521 - faraday_agent_dispatcher - WARNING {MainThread} [dispatcher.py:475 - run_once()]  Executor openvas finished with exit code 1
```
If I remove the _filter_ argument in the below call in `/usr/local/lib/python3.10/dist-packages/faraday_agent_dispatcher/static/executors/official/gvm_openvas.py` the error stops occuring. However, no results are imported.
```
 # Get report
    with Gmp(connection=connection, transform=transform) as gmp:
        gmp.authenticate(user, passw)

        report = gmp.get_report(
            report_id=report_id,
            report_format_id=xml_format,
            filter="apply_overrides=0 levels=hml rows=-1 min_qod=70 "
            "first=1 sort-reverse=severity "
            "notes=0 overrides=0",
            details=True,
        )
```
**OS:** Kali Linux 2022.3
**Faraday version:** 4.1.0
**faraday_agent_dispatcher:** 2.3.0
**OpenVAS version:** 21.4.3

**Comment by gmartinez95** [comment]
Hi @lospoelos 
We look at the problem and it will be fixed in the next release. Meantime if you change filter by filter_string should fix the problem

**Comment by lospoelos** [comment]
That fixed it for me. Thank you so much.
